### ISSUE TITLE
FileNotFoundError:inat_clip_a+cname_hrchy_l1.npy

### ISSUE THREAD

**Issue by zhongzee** [naver/shine#2]
Thank you for your excellent work.
When I execute the following code bash scripts_local/CoDet/inat/rn50/inat_codet_rn50_baseline.sh, an error is reported;
FileNotFoundError: [Errno 2] No such file or directory: 'nexus/inat/vitB32/shine_llm/inat_clip_a+cname_hrchy_l1.npy';
How can I get this file? Thank you very much for your reply.

**Comment by OatmealLiu** [comment]
Hi! Thank you for pointing this out. This is due to the incorrect file names "inat_clip_a+cname_hrchy_xx.npy" (incorrect) in the scripts under  scripts_local/CoDet/inat and  scripts_slurm/CoDet/inat folders. I have fixed the file names to the correct ones "inat_clip_hrchy_xx.npy" (correct) in the scripts. Thank you!
