### ISSUE TITLE
Discrepancy in Candidate Sentences Construction between iNat and FSOD Datasets

### ISSUE THREAD

**Issue by zhongzee** [naver/shine#6]
Hi,

I noticed an inconsistency between the iNat and FSOD dataset implementations regarding the construction of `candidate_sentences`:

For the iNat dataset, it appears that the `candidate_sentences` are generated using only the first parent node (e.g., "Cyprinidae"). However, for the FSOD dataset, each `candidate_sentence` includes all parent nodes (e.g., "matter", "fluid", etc.). 

Could you provide some clarification on why this discrepancy exists? Is it intentional, and if so, what is the rationale behind using only the first parent node for iNat but all parent nodes for FSOD?

Thanks for your time, and I look forward to your response!
![caf7a85536ff5d9361be30cb171a375](https://github.com/user-attachments/assets/04e9e081-9282-4203-bc44-405bd74290fb)
![c19acb77952ada87816f88786fb5f41](https://github.com/user-attachments/assets/f8618867-f361-43f7-849b-e4362800b4d9)

**Comment by OatmealLiu** [comment]
Hi. Please refer as to the additional construction description in the main paper and appenxi-when LLM-generated hierarchy is used, all super-/sub-categories are iteratively used. The "discrepancy" you mentioned between iNat and FSOD is not about how we use it. It is because iNat categories have unique, single parent node at each level following the hierarchy tree of life (because they are animal species). FSOD are common objects, therefore, each category might have multiple parent categories as well.
